MyApp.WebMvc03/Controllers/Admin/Security/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyApp.Admin.Security.Public.Constants;
using MyApp.Admin.Security.Public.Dtos;
using MyApp.Admin.Security.Public.Enums;
using MyApp.Admin.Security.Public.PermissionControl.Policy;
using MyApp.Admin.Security.Public.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyApp.WebMvc03.Controllers.Admin.Security
{
    public class UserRolesController : Controller
    {
        private static readonly string _viewFolder = "/Views/Admin/Security/UserRoles/";

        [HasPermission(Permissions.UserRoleView)]
        public async Task<IActionResult> Index([FromServices] IUserRoleService service)
        {
            var userRolesList = await service.ListAllUsersWithRolesAsync();
            return View($"{_viewFolder}Index.cshtml", userRolesList);
        }

        [HasPermission(Permissions.UserRoleManage)]
        public async Task<IActionResult> Manage(string userId, [FromServices] IUserRoleService service)
        {
            ViewBag.userId = userId;
            var user = await service.GetUserProfileAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = await service.ListUserRolesForManageViewAsync(user);
            return View($"{_viewFolder}Manage.cshtml", model);
        }

        [HasPermission(Permissions.UserRoleManage)]
        [HttpPost]
        public async Task<IActionResult> Manage(
            List<UserRoleAssignedData> model, string userId, 
            [FromServices] IUserRoleService service,
            [FromServices] ICacheControlService cacheService)
        {
            var user = await service.GetUserProfileAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            
            await cacheService.UpdateLastRefreshTimeAsync(CacheKeys.USER_PERMISSIONS, false);

            var roles = await service.ListRolesAssignedToUserAsync(user);
            var result = await service.RemoveRolesFromUserAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await service.AddRolesToUserAsync(
                user, 
                model.Where(x => x.IsAssigned)
                    .Select(y => y.RoleName)
            );
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
    }
}

MyApp.WebMvc03/Controllers/School/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MyApp.Admin.Security.Public.Enums;
using MyApp.Admin.Security.Public.PermissionControl.Policy;
using MyApp.School.Public.Dtos;
using MyApp.School.Public.Services;
using MyApp.WebMvc03.Utils;
using System;
using System.Threading.Tasks;

namespace MyApp.WebMvc03.Controllers.School
{
    public class CoursesController : Controller
    {
        private readonly ILogger<CoursesController> _logger;

        private static readonly string _viewFolder = "/Views/School/Courses/";

        public CoursesController(ILogger<CoursesController> logger)
        {
            _logger = logger;
        }

        [HasPermission(Permissions.CourseView)]
        // GET: Courses
        public async Task<IActionResult> Index([FromServices] ICourseService service)
        {
            return View($"{_viewFolder}Index.cshtml", await service.ListAllCoursesAsync());
        }

        [HasPermission(Permissions.CourseView)]
        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id, [FromServices] ICourseService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var course = await service.GetCourseByIdForDetailAsync(id.Value);
            if (course == null)
            {
                return NotFound();
            }

            return View($"{_viewFolder}Details.cshtml", course);
        }

        [HasPermission(Permissions.CourseAdd)]
        // GET: Courses/Create
        public async Task<IActionResult> Create([FromServices] ICourseService service)
        {
            await PopulateDepartmentsDropDownListAsync(service);
            return View($"{_viewFolder}Create.cshtml");
        }

        private async Task PopulateDepartmentsDropDownListAsync(ICourseService service, object selectedDepartment = null)
        {
            ViewBag.DepartmentOptions = new SelectList(
                await service.ListAllDepartmentOptionsAsync(), 
                "DepartmentId", "DepartmentName", 
                selectedDepartment);
        }

        [HasPermission(Permissions.CourseAdd)]
        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            CourseAddEditDto courseDto, [FromServices] ICourseService service)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.CreateCourseAndSaveAsync(courseDto);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", Constants.ERROR_MESSAGE_SAVE);
                }
            }
            await PopulateDepartmentsDropDownListAsync(service);
            return View($"{_viewFolder}Create.cshtml", courseDto);
        }

        [HasPermission(Permissions.CourseEdit)]
        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id, [FromServices] ICourseService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var course = await service.GetCourseByIdForEditAsync(id.Value);
            if (course == null)
            {
                return NotFound();
            }
            await PopulateDepartmentsDropDownListAsync(service, course.DepartmentId);
            return View($"{_viewFolder}Edit.cshtml", course);
        }

        [HasPermission(Permissions.CourseEdit)]
        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(
            CourseAddEditDto courseDto, [FromServices] ICourseService service)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.UpdateCourseAndSaveAsync(courseDto);
                }
                catch (Exception)
                {
                    //_logger.LogError(ex, "Failed to edit Course: id={id}", id);
                    ModelState.AddModelError("", Constants.ERROR_MESSAGE_SAVE);
                }
                return RedirectToAction(nameof(Index));
            }
            await PopulateDepartmentsDropDownListAsync(service, courseDto.DepartmentId);
            return RedirectToAction(nameof(Index));
        }

        [HasPermission(Permissions.CourseDelete)]
        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id, [FromServices] ICourseService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var course = await service.GetCourseByIdForDetailAsync(id.Value);
            if (course == null)
            {
                return NotFound();
            }

            return View($"{_viewFolder}Delete.cshtml", course);
        }

        [HasPermission(Permissions.CourseDelete)]
        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(int? id, [FromServices] ICourseService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            await service.DeleteCourseAndSaveAsync(id.Value);
            return RedirectToAction(nameof(Index));
        }

    }
}

MyApp.WebMvc03/Controllers/School/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyApp.Admin.Security.Public.Enums;
using MyApp.Admin.Security.Public.PermissionControl.Policy;
using MyApp.Common.Public.Dtos;
using MyApp.Common.Public.Exceptions;
using MyApp.School.Public.Dtos;
using MyApp.School.Public.Services;
using MyApp.WebMvc03.Utils;
using System;
using System.Threading.Tasks;

namespace MyApp.WebMvc03.Controllers.School
{
    public class StudentsController : Controller
    {
        private readonly ILogger<StudentsController> _logger;

        private static readonly string _viewFolder = "/Views/School/Students/";

        public StudentsController(ILogger<StudentsController> logger)
        {
            _logger = logger;
        }

        [HasPermission(Permissions.StudentView)]
        // GET: Students
        public async Task<IActionResult> Index(
            ListingFilterSortPageDto filterSortPageDto, [FromServices] IStudentService service)
        {
            PaginatedList<StudentListItem> paginatedList = null;

            try
            {
                paginatedList = await service.ListAllStudentsAsync(filterSortPageDto);

                // set the final page index based on the latest database records available
                filterSortPageDto.PageIndex = paginatedList.PaginationInfo.PageIndex;
            }
            catch (GeneralException ex)
            {
                _logger.LogError("GeneralException in Index: " + ex.Message);
                ViewBag.HasError = true;
                ViewBag.Message = ex.Message;
            }
            catch (Exception ex)
            {
                _logger.LogError("Exception in Index: " + ex.Message);
                ViewBag.HasError = true;
                ViewBag.Message = Constants.ERROR_MESSAGE_STANDARD + ": " + ex.Message;
            }

            var studentListDto = new StudentListDto(paginatedList, filterSortPageDto);

            return View($"{_viewFolder}Index.cshtml", studentListDto);
        }

        [HasPermission(Permissions.StudentView)]
        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id, [FromServices] IStudentService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var student = await service.GetStudentByIdForDetailAsync(id.Value);
            if (student == null)
            {
                return NotFound();
            }

            return View($"{_viewFolder}Details.cshtml", student);
        }

        [HasPermission(Permissions.StudentAdd)]
        // GET: Students/Create
        public IActionResult Create()
        {
            return View($"{_viewFolder}Create.cshtml");
        }

        [HasPermission(Permissions.StudentAdd)]
        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            StudentAddEditDto student, [FromServices] IStudentService service)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.CreateStudentAndSaveAsync(student);
                    TempData["Message"] = Constants.SUCCESS_MESSAGE;
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    _logger.LogError("Error in Create: " + ex.Message);
                    ViewBag.HasError = true;
                    ViewBag.Message = Constants.ERROR_MESSAGE_SAVE + ": " + ex.Message;
                }
            }

            return View($"{_viewFolder}Create.cshtml", student);
        }

        [HasPermission(Permissions.StudentEdit)]
        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id, [FromServices] IStudentService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var student = await service.GetStudentByIdForEditAsync(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            return View($"{_viewFolder}Edit.cshtml", student);
        }

        [HasPermission(Permissions.StudentEdit)]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(
            int? id, StudentAddEditDto studentDto, [FromServices] IStudentService service)
        {
            if (!id.HasValue
                || id.Value != studentDto.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await service.UpdateStudentAndSaveAsync(studentDto);
                    TempData["Message"] = Constants.SUCCESS_MESSAGE;
                    return RedirectToAction(nameof(Index));
                }
                catch (GeneralException ex)
                {
                    ViewBag.HasError = true;
                    ViewBag.Message = ex.Message;
                }
                catch (Exception ex)
                {
                    ViewBag.HasError = true;
                    ViewBag.Message = Constants.ERROR_MESSAGE_STANDARD + ": " + ex.Message;
                }
            }

            return View($"{_viewFolder}Edit.cshtml", studentDto);
        }

        [HasPermission(Permissions.StudentDelete)]
        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(
            int? id, [FromServices] IStudentService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var hasPreviousError = TempData["HasError"] != null && Convert.ToBoolean(TempData["HasError"]);
            var message = Convert.ToString(TempData["Message"]);

            var student = await service.GetStudentByIdForDetailAsync(id.Value);
            if (student == null)
            {
                // deleted by another user in previous delete request
                if (hasPreviousError)
                {
                    TempData["Message"] = message;
                    TempData["HasError"] = hasPreviousError;
                    return RedirectToAction(nameof(Index));
                }
                return NotFound(); // new delete request
            }

            return View($"{_viewFolder}Delete.cshtml", student);
        }

        [HasPermission(Permissions.StudentDelete)]
        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(
            int? id, [FromServices] IStudentService service)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            try
            {
                await service.DeleteStudentAndSaveAsync(id.Value);
                TempData["Message"] = Constants.SUCCESS_MESSAGE;
                return RedirectToAction(nameof(Index));
            }
            catch (GeneralException ex)
            {
                TempData["Message"] = ex.Message;
                TempData["HasError"] = true;
                return RedirectToAction(nameof(Delete), new { id = id.Value });
            }
            catch (Exception ex)
            {
                TempData["Message"] = Constants.ERROR_MESSAGE_STANDARD + ": " + ex.Message;
                TempData["HasError"] = true;
                return RedirectToAction(nameof(Delete), new { id = id.Value });
            }
        }

    }
}

MyApp.WebMvc03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contoso University</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contoso University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.HasPermission(Permissions.StudentView)
                              || User.HasPermission(Permissions.CourseView)
                              || User.HasPermission(Permissions.InstructorView)
                              || User.HasPermission(Permissions.DepartmentView))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                                       data-toggle="dropdown" aria-expanded="false">
                                        School
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                        @if (User.HasPermission(Permissions.StudentView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                                            </li>
                                        }
                                        @if (User.HasPermission(Permissions.CourseView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                                            </li>
                                        }
                                        @if (User.HasPermission(Permissions.InstructorView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Instructors" asp-action="Index">Instructors</a>
                                            </li>
                                        }
                                        @if (User.HasPermission(Permissions.DepartmentView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                            }
                            @if (User.HasPermission(Permissions.RoleView)
                               || User.HasPermission(Permissions.UserRoleView))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                                       data-toggle="dropdown" aria-expanded="false">
                                        Admin
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                        @if (User.HasPermission(Permissions.RoleView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                                            </li>
                                            @*<li><hr class="dropdown-divider"></li>*@
                                        }
                                        @if (User.HasPermission(Permissions.UserRoleView))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="UserRoles" asp-action="Index">User Roles</a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <partial name="_SystemMessagePartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Contoso University - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha512-TqmAh0/sSbwSuVBODEagAoiUIeGRo8u95a41zykGfq5iPkO9oie8IKCgx7yAr1bfiBjZeuapjLgMdp9UMpCVYQ==">
        </script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    @*Render any script files to be included for current page load*@
    @{
        var scriptNameList = ViewData["ScriptNameList"] as IEnumerable<string>;

        if (scriptNameList != null && scriptNameList.Any())
        {
            foreach (var scriptName in scriptNameList)
            {
                <script src="@scriptName" asp-append-version="true"></script>
            }
        }
    }
</body>
</html>

MyApp.WebMvc03/Views/Shared/_PaginationPartial.cshtml
@using MyApp.Common.Public.Dtos

@model PaginationDto

@{
    var prevDisabled = Model.HasPreviousPage ? "" : "disabled";
    var nextDisabled = Model.HasNextPage ? "" : "disabled";

    var currentPageNo = Model.PageIndex;
    var totalPages = Model.TotalPages;
}
<div class="row">
    <div class="text-left col-sm-4">
        <a class="btn btn-primary @prevDisabled" href="#" id="BtnPreviouPage">
            Previous
        </a>
        <a class="btn btn-primary @nextDisabled" href="#" id="BtnNextPage">
            Next
        </a>
    </div>
    <div class="text-center font-weight-bold col-sm-4 mb-2 mt-2">
        Page @currentPageNo of @totalPages
    </div>
    <div class="font-weight-bold col-sm-4">
        <div class="row">
            <div class="col-auto">
                <select asp-for="PageSize" id="PageSize" name="PageSize"
                        asp-items="Html.GetEnumSelectList<PageSizeOptions>()"
                        class="form-control m-0"></select>
            </div>
            <div class="col-auto">
                Rows Per Page
            </div>
        </div>
    </div>
</div>

MyApp.WebMvc03/Views/Shared/_SystemMessagePartial.cshtml
@{
    // try to load any values from TempData first, if not available then check on ViewBag

    if (!String.IsNullOrWhiteSpace((string)TempData["Message"])
        || !String.IsNullOrWhiteSpace(ViewBag.Message))
    {
        bool hasError = false;
        if (TempData["HasError"] != null)
        {
            hasError = (bool)TempData["HasError"];
        }
        else if (ViewBag.HasError != null)
        {
            hasError = ViewBag.HasError;
        }

        var message = (string)TempData["Message"] ?? ViewBag.Message;

        var alertClass = "alert alert-success alert-dismissible show fade";
        if (hasError)
        {
            alertClass = "alert alert-danger alert-dismissible show fade";
        }

    <div class="@alertClass" role="alert">
        <h6 class="text-left">
            @{ WriteLiteral(message); }
        </h6>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    }
}